### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by DavidZhiXing** [DavidZhiXing/2021#1]
记录每天想做的事

- [x] github trending
- [x] microsft document
- [x] #4
- [x] write an article
- [x] twitter message
- [x] #2
- [x] #3

**Comment by DavidZhiXing** [comment]
- [x] #8 
- [x] #7 
- [x] #9 
- [x] calligraphy
- [x] buy tickets
- [ ] swingming
- [ ] running
- [x] use deepl
- [x] refine goals
- [x] update todo list
- [x]  twitter message
- [x] reply a twitter message

**Comment by DavidZhiXing** [comment]
twitter message is not a goog goal. Can refine it as:

- [x] read a twitter message
- [x] star a twitter message
- [x] write a twitter message
- [x] read all unread message [ but no more than 50 messages]

**Comment by DavidZhiXing** [comment]
- [x] using deepl
- [x] find a good repo: [wifi card](https://wificard.io/) 
- [x] github trending 
- [x] [read wiki about laser](https://en.wikipedia.org/wiki/Laser)
- [x] update profile
- [x] git hub project
- [x] git hub action

**Comment by DavidZhiXing** [comment]
- [x] #11 
- [x] #12

**Comment by DavidZhiXing** [comment]
- [ ] 如何在不玩游戏的情况了解游戏业务？
- [ ] 如何在没有相应技术的情况下做成产品？
- [ ] 没有资金如何打造团队？
- [ ] 如何找到要做事情的切入点？
- [ ] 深圳要什么机会？
- [ ] 如何去帮助团队实现目标？
- [ ] 如何把自己的状态整理好？不会去玩游戏，看小说，刷社交软件？
- [ ] 如何找到小的目标去实现？
- [ ] 如何让投资人的相信你？
- [ ] 为什么放弃技术？
- [ ] 什么是团队型人才？
- [ ] 什么是销售型人才？
- [ ] 什么是技术型人才？
- [ ] 要设定什么目标？
